apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchandise
spec:
  replicas: 3
  selector:
    matchLabels:
      app: merchandise
  template:
    metadata:
      labels:
        app: merchandise
    spec:
      containers:
      - name: merchandise
        image: <ECR_REGISTRY>/merchandise:<IMAGE_TAG>
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: merchandise
spec:
  selector:
    app: merchandise
  ports:
    - port: 80
      targetPort: 3003
  type: LoadBalancer