
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: e-commerce/frontend
        tag_with_ref: true
        dockerfile: Dockerfiles/Dockerfile.frontend
        
  build-merchandise:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push merchandise image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: e-commerce/merchandise
        tag_with_ref: true
        dockerfile: Dockerfiles/Dockerfile.merchandise
        
  build-products:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push products image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: e-commerce/products
        tag_with_ref: true
        dockerfile: Dockerfiles/Dockerfile.products
        
  build-shopping-cart:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push shopping-cart image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: e-commerce/shopping-cart
        tag_with_ref: true
        dockerfile: Dockerfiles/Dockerfile.shopping-cart
        
  deploy:
    needs: [build-frontend, build-merchandise, build-products, build-shopping-cart]
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      CLUSTER_NAME: my-eks-cluster
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform init
      run: |
        cd terraform
        terraform init
        
    - name: Terraform apply
      run: |
        cd terraform
        terraform apply -auto-approve
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Deploy to EKS
      run: |
        # Deploy Kubernetes resources
        kubectl apply -f kubernetes/