name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'escriba "DEPLOY" para confirmar'
        required: true

jobs:
  validate-confirmation:
    runs-on: ubuntu-latest
    steps:
    - name: Check confirmation word
      run: |
        if [ "${{ github.event.inputs.confirmation }}" != "DEPLOY" ]; then
          echo "La palabra de confirmación no es correcta. El pipeline no se ejecutará."
          exit 1
        fi

  destroy:
    needs: validate-confirmation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve